owner: jln-brtn # Your GitHub organization or username, where this repository lives
repo: statusbase-reborn # The name of this repository
branch: master # The name of the branch

status-website:
  cname: demo.statusbase-reborn.julien-breton.fr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Statusbase Reborn Demo
  description: Demo of the Statusbase Reborn project

groups:
  - name: "French Zone"
    slug: "fr-zone"
    sites:
      - name: Google
        desc: https://www.google.fr/
        slug: fr-google
      - name: Hugging Face
        desc: https://huggingface.co/
        slug: fr-hugging-face
      - name: MistralAI
        desc: https://mistral.ai/fr/
        slug: fr-mistral-ai
  - name: "UK Zone"
    slug: "uk-zone"
    sites:
      - name: Failure Website
        desc: http://cesitenexistepas.com/
        slug: uk-failure-website