name: [DEMO] Scheduled Health Check
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run check script
        run: ./build/main
        working-directory: ci

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Add executables to Git
        run: git add ./ci/logs/*

      - name: Commit logs
        id: commit
        run: |
          git diff-index --quiet HEAD || git commit -m "Update health check logs"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
