name: Initialization

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.5'

      - name: Change directory to ci
        run: cd ci

      - name: Install dependencies
        run: go mod download
        working-directory: ci

      - name: Build
        run: go build -v -o ./build/check ./script/check.go
        working-directory: ci